#!/usr/bin/env python
import sys
import os
import glob
import requests


if len(sys.argv) > 4:
    status = sys.argv[2]
    fname = sys.argv[4]
elif len(sys.argv) == 3:
    status = sys.argv[1]
    fname = sys.argv[2]
else:
    status = 'update'
    fname = sys.argv[1]

print(status, fname)

if status in ['playing', 'update', 'left', 'right']:
    pattern = os.path.join(
        glob.escape(os.path.dirname(fname)),
        'cover.*')
    print(pattern)
    cover = glob.glob(pattern)
    print(cover)
    if len(cover):
        print('Setting cover', status)
        requests.get(
            'http://127.0.0.1:34543/load_img',
            params={'path': os.path.abspath(cover[0]).encode('utf-8'),
                    'loc': status})
    else:
        requests.get('http://127.0.0.1:34543/load_img',
                     params={'loc': status})
